### ISSUE TITLE
Variable fonts and Italic for sentient

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#61]
With variable fonts is better to write the @fontface like this:

```CSS
@font-face {
  font-family: 'Sentient-Variable';
  src: url('../fonts/Sentient-Variable.woff2') format('woff2'),
       url('../fonts/Sentient-Variable.woff') format('woff'),
       url('../fonts/Sentient-Variable.ttf') format('truetype');
       font-weight: 200 700;
       font-display: swap;
       font-style: normal;
}

```
For Sentient Italic please use Sentient-VariableItalic, since it's another file, modify the css like this: 

```CSS
@font-face {
  font-family: 'Sentient-Variable';
  src: url('../fonts/Sentient-VariableItalic.woff2') format('woff2'),
       url('../fonts/Sentient-VariableItalic.woff') format('woff'),
       url('../fonts/Sentient-VariableItalic.ttf') format('truetype');
       font-weight: 200 700;
       font-display: swap;
       font-style: italic;
}
```

I attach screenshot of how it should look and how it looks and the italic fonts. 

![Screenshot 2022-05-04 at 14 39 02](https://user-images.githubusercontent.com/2106518/166684306-b83eac38-f33e-4040-b76a-25cbbe336ef5.png)

[SentientItalic.zip](https://github.com/C2DH/minett-stories/files/8620439/SentientItalic.zip)
